version: '3'
services:
  locast2tuner:
    image: ghcr.io/wouterdebie/locast2tuner:latest
    container_name: locast2tuner
    volumes:
      - ./.locast2tuner:/app/config
    ports:
      - 6077:6077
    restart: unless-stopped
